---

dist: bionic
language: python

sudo: false

# Install ansible.
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible-lint

before_script:
  - ansible-lint --version

script:
  - git ls-files | grep -Ei '^[^[:punct:]].+.(yaml|yml)$' | xargs ansible-lint -q
  - ls -1 *.yml | xargs ansible-playbook --syntax-check --list-tasks --vault-password-file=.vault.txt -i 127.0.0.1,
