---

- name: "Manage Jenkins with NSSM."
  win_nssm:
    name: Jenkins
    application: "{{ jenkins_path }}"
    start_mode: auto
    state: started
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_password }}"
    dependencies: 'dnscache,netlogon'
